todo/urls.py
from django.conf.urls import url
from todo import views

urlpatterns = [
    url(r'^$', views.list_lists, name="todo-lists"),
    url(r'^mine/$', views.view_list, {'list_slug': 'mine'}, name="todo-mine"),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)/delete$', views.del_list, name="todo-del_list"),
    url(r'^task/(?P<task_id>\d{1,6})$', views.view_task, name='todo-task_detail'),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)$', views.view_list, name='todo-incomplete_tasks'),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)/completed$', views.view_list, {'view_completed': True},
        name='todo-completed_tasks'),
    url(r'^add_list/$', views.add_list, name="todo-add_list"),
    url(r'^search-post/$', views.search_post, name="todo-search-post"),
    url(r'^search/$', views.search, name="todo-search"),

    # View reorder_tasks is only called by JQuery for drag/drop task ordering
    url(r'^reorder_tasks/$', views.reorder_tasks, name="todo-reorder_tasks"),

    url(r'^ticket/add/$', views.external_add, name="todo-external-add"),
    url(r'^recent/added/$', views.view_list, {'list_slug': 'recent-add'}, name="todo-recently_added"),
    url(r'^recent/completed/$', views.view_list, {'list_slug': 'recent-complete'},
        name="todo-recently_completed"),
]

todo/models.py
from __future__ import unicode_literals
import datetime

from django.db import models
from django.contrib.auth.models import Group
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.conf import settings
from autoslug import AutoSlugField


@python_2_unicode_compatible
class List(models.Model):
    name = models.CharField(max_length=60)
    slug = AutoSlugField(populate_from='name', editable=False, always_update=True)
    group = models.ForeignKey(Group)

    def __str__(self):
        return self.name

    def incomplete_tasks(self):
        # Count all incomplete tasks on the current list instance
        return Item.objects.filter(list=self, completed=0)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Lists"

        # Prevents (at the database level) creation of two lists with the same name in the same group
        unique_together = ("group", "slug")


@python_2_unicode_compatible
class Item(models.Model):
    title = models.CharField(max_length=140)
    list = models.ForeignKey(List)
    created_date = models.DateField(auto_now=True)
    due_date = models.DateField(blank=True, null=True, )
    completed = models.BooleanField(default=None)
    completed_date = models.DateField(blank=True, null=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='todo_created_by')
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name='todo_assigned_to')
    note = models.TextField(blank=True, null=True)
    priority = models.PositiveIntegerField()

    # Has due date for an instance of this object passed?
    def overdue_status(self):
        "Returns whether the item's due date has passed or not."
        if self.due_date and datetime.date.today() > self.due_date:
            return 1

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('todo-task_detail', kwargs={'task_id': self.id, })

    # Auto-set the item creation / completed date
    def save(self):
        # If Item is being marked complete, set the completed_date
        if self.completed:
            self.completed_date = datetime.datetime.now()
        super(Item, self).save()

    class Meta:
        ordering = ["priority"]


@python_2_unicode_compatible
class Comment(models.Model):
    """
    Not using Django's built-in comments because we want to be able to save
    a comment and change task details at the same time. Rolling our own since it's easy.
    """
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    task = models.ForeignKey(Item)
    date = models.DateTimeField(default=datetime.datetime.now)
    body = models.TextField(blank=True)

    def snippet(self):
        # Define here rather than in __str__ so we can use it in the admin list_display
        return "{author} - {snippet}...".format(author=self.author, snippet=self.body[:35])

    def __str__(self):
        return self.snippet

todo/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import Group
from todo.models import Item, List
from django.contrib.auth import get_user_model


class AddListForm(ModelForm):
    # The picklist showing allowable groups to which a new list can be added
    # determines which groups the user belongs to. This queries the form object
    # to derive that list.
    def __init__(self, user, *args, **kwargs):
        super(AddListForm, self).__init__(*args, **kwargs)
        self.fields['group'].queryset = Group.objects.filter(user=user)

    class Meta:
        model = List
        exclude = []


class AddItemForm(ModelForm):
    # The picklist showing the users to which a new task can be assigned
    # must find other members of the groups the current list belongs to.
    def __init__(self, task_list, *args, **kwargs):
        super(AddItemForm, self).__init__(*args, **kwargs)
        # print dir(self.fields['list'])
        # print self.fields['list'].initial
        self.fields['assigned_to'].queryset = get_user_model().objects.filter(groups__in=[task_list.group])
        self.fields['assigned_to'].label_from_instance = \
            lambda obj: "%s (%s)" % (obj.get_full_name(), obj.username)

    due_date = forms.DateField(
        required=False,
        widget=forms.DateTimeInput(attrs={'class': 'due_date_picker'})
    )

    title = forms.CharField(
        widget=forms.widgets.TextInput(attrs={'size': 35})
    )

    note = forms.CharField(widget=forms.Textarea(), required=False)

    class Meta:
        model = Item
        exclude = []


class EditItemForm(ModelForm):
    # The picklist showing the users to which a new task can be assigned
    # must find other members of the groups the current list belongs to.
    def __init__(self, *args, **kwargs):
        super(EditItemForm, self).__init__(*args, **kwargs)
        self.fields['assigned_to'].queryset = get_user_model().objects.filter(groups__in=[self.instance.list.group])

    class Meta:
        model = Item
        exclude = ('created_date', 'created_by',)


class AddExternalItemForm(ModelForm):
    """Form to allow users who are not part of the GTD system to file a ticket."""

    title = forms.CharField(
        widget=forms.widgets.TextInput(attrs={'size': 35})
    )
    note = forms.CharField(
        widget=forms.widgets.Textarea(),
        help_text='Foo',
    )

    class Meta:
        model = Item
        exclude = ('list', 'created_date', 'due_date', 'created_by', 'assigned_to',)


class SearchForm(forms.Form):
    """Search."""

    q = forms.CharField(
        widget=forms.widgets.TextInput(attrs={'size': 35})
    )

todo/templates/todo/add_external_task.html
{% extends "todo/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}File Ticket{% endblock %}

{% block content %}

    <h2>{{ task }}</h2>

    <form action="" method="POST">
        {% csrf_token %}

        {% if task.note %}
            <div class="task_note"><strong>Note:</strong> {{ task.note|safe|urlize|linebreaks }}</div>
        {% endif %}

        <div id="TaskEdit">
            <h3>File Trouble Ticket</h3>
            <p>Trouble with a computer or other technical system at the J-School? <br />
            Use this form to report the difficulty - we'll get right back to you. </p>

            {% if form.errors %}

                {% for error in form.errors %}
                    <ul class="errorlist">
                        <li><strong>The {{ error|escape }} field is required.</strong></li>
                    </ul>
                {% endfor %}
                <br />

            {% endif %}

            <table>
                <tr>
                    <td>Summary:</td>
                    <td>{{ form.title }} <br />
                        Include the workstation number in your summary, e.g. <br />
                        "Radio Lab # 4: Purple smoke pouring out the back."
                     </td>
                </tr>

                <tr>
                    <td valign="top">Note:</td>
                    <td valign="top">{{ form.note }}<br />
                        Please describe the problem.
                    </td>
                </tr>

                <tr>
                    <td>Priority:</td>
                    <td>{{ form.priority }} <br />
                        Enter a number between 1 and 5, <br />
                        where 5 is highest ("Computer is on fire = True").
                     </td>
                </tr>
            </table>
            <p><input type="submit" class="todo-button" name="add_task" value="Submit"></p>
        </div>
    </form>
{% endblock %}

todo/templates/todo/add_list.html
{% extends "todo/base.html" %}

{% block page_heading %}{% endblock %}
{% block title %}Add Todo List{% endblock %}

{% block content %}

	<h2>Add a list:</h2>

	<form action="" method="post">
		{% csrf_token %}
	<table>{{ form }}</table>
	<p><input type="submit" value="Submit" class="todo-button"></p>
	</form>

{% endblock %}

todo/templates/todo/base.html
{% extends "base.html" %}
{% load staticfiles %}

{% block extrahead %}
	<!-- CSS and JavaScript for django-todo -->
	<link rel="stylesheet" type="text/css" href="{% static 'todo/css/styles.css' %}" />
	<script src="{% static 'todo/js/jquery.tablednd_0_5.js' %}" type="text/javascript"></script>
	<script type="text/javascript" charset="utf-8">
	    // thedate.x comes from the edit_task view. If this is a new entry,
	    // thedate won't be present and datepicker will fall back on the default (today).
	    $(document).ready(function(){
	        $('#id_due_date').datepicker({defaultDate: new Date({{thedate.year}}, {{thedate.month}} - 1, {{thedate.day}}),});
	     });
	</script>
{% endblock extrahead %}

todo/templates/todo/del_list.html
{% extends "todo/base.html" %}

{% block title %}{{ list_title }} to-do items{% endblock %}

{% block content %}

    {% if user.is_staff %}
        <h1>Delete entire list: {{ list.name }} ?</h1>

        <p>Category tally:</p>

         <ul>
            <li>Incomplete: {{ item_count_undone }} </li>
            <li>Complete: {{ item_count_done }} </li>
            <li><strong>Total: {{ item_count_total }}</strong> </li>
         </ul>

        <p> ... all of which will be irretrievably <strong>blown away</strong>. Are you sure you want to do that?</p>

        <form action="" method="post" accept-charset="utf-8">
		    {% csrf_token %}
            <input type="hidden" name="list" value="{{ list.id }}" id="some_name">
            <p><input type="submit" name="delete-confirm" value="Do it! &rarr;" class="todo-button"> </p>
        </form>

        <a href="{% url 'todo-incomplete_tasks' list.id list_slug %}">Return to list: {{ list.name }}</a>

    {% else %}
        <p>Sorry, you don't have permission to delete lists. Please contact your group administrator.</p>
    {% endif %}

{% endblock %}

todo/templates/todo/list_lists.html
{% extends "todo/base.html" %}

{% block title %}{{ list_title }} Todo Lists{% endblock %}

{% block content %}

   <h1>Todo Lists</h1>

   <p>{{ item_count }} items in {{ list_count }} lists</p>

   	{% regroup list_list by group as section_list %}

    {% for group in section_list %}
        <h3>{{ group.grouper }}</h3>
        <ul>
            {% for item in group.list %}
   	            <li><a class="todo" href="{% url 'todo-incomplete_tasks' item.id item.slug %}">{{ item.name }} </a> ({{ item.incomplete_tasks.count }}/{{ item.item_set.count }})</li>
            {% endfor %}
        </ul>
    {% endfor %}

    <p><a href="{% url 'todo-add_list' %}">Create new todo list</a></p>

{% endblock %}

todo/templates/todo/search_results.html
{% extends "todo/base.html" %}

{% block title %}Search results{% endblock %}

{% block content_title %}
    <h2 class="page_title">Search</h2>
{% endblock %}

{% block content %}
    {% if found_items %}
        <h2>{{found_items.count}} search results for term: "{{ query_string }}"</h2>
        <div class="post_list">
            {% for f in found_items %}
                <p><strong><a href="{% url 'todo-task_detail' f.id %}">{{ f.title }}</a></strong><br />
                    <span class="minor">
                        On list: <a href="{% url 'todo-incomplete_tasks' f.list.id f.list.slug %}">{{ f.list.name }}</a><br />
                        Assigned to: {% if f.assigned_to %}{{ f.assigned_to }}{% else %}Anyone{% endif %} (created by: {{ f.created_by }})<br />
                        Complete: {{ f.completed|yesno:"Yes,No" }}
                    </span>
                </p>
            {% endfor %}
        </div>
    {% else %}
        <h2> No results to show, sorry.</h2>
    {% endif %}
{% endblock %}

todo/templates/todo/view_list.html
{% extends "todo/base.html" %}

{% block title %}Todo List: {{ list.name }}{% endblock %}

{% block content %}
    <script type="text/javascript">
        function order_tasks(data) {
            // The JQuery plugin tableDnD provides a serialize() function which provides the re-ordered
            // data in a list. We pass that list as an object called "data" to a Django view
            // to save the re-ordered data into the database.

            $.post("{% url 'todo-reorder_tasks' %}", data, "json");
            return false;
        };

        $(document).ready(function() {
            // Initialise the task table for drag/drop re-ordering
            $("#tasktable").tableDnD();

            $('#tasktable').tableDnD({
                onDrop: function(table, row) {
                    order_tasks($.tableDnD.serialize());
                }
            });

            // Initially hide the Add Task form
            $('#AddTask').hide();

            // toggle slide to show the Add Task form when link clicked
            $('#slideToggle').click(function(){
                $(this).siblings('#AddTask').slideToggle();
            });
        });
    </script>

    {% if list_slug == "mine" %}
        <h1>Tasks assigned to {{ request.user }}</h1>
    {% elif auth_ok %}
       <h1>Tasks filed under "{{ list.name }}"</h1>
       <p>This list belongs to group {{ list.group }}</p>
    {% endif %}

    {% if auth_ok %}
        <form action="" method="POST">
            {% csrf_token %}

            {# Only show task adder if viewing a proper list #}
            {% if list_slug != "mine" %}
                <h2 style="margin-bottom:0px;" id="slideToggle" >&rarr; Click to add task &larr;</h2>

                <div id="AddTask">
            	    <table class="nocolor" border="0" cellspacing="5" cellpadding="5">
            	       <tr>
            	           <td>{{ form.title.errors }}</td>
            	           <td>{{ form.due_date.errors }}</td>
            	       </tr>
            	       <tr>
            	           <td><label for="id_title">Task:</label> {{ form.title }}</td>
            	           <td><label for="id_due_date">Due date:</label> {{ form.due_date }}</td>
            	           <td><label for="id_assigned">Assign to:</label> {{ form.assigned_to }}</td>
            	           <td><label for="id_notify">Notify*:</label> <input type="checkbox" checked="checked" name="notify" value="1" id="notify"></td>
             	       </tr>
            	       <tr>
            	           <td><label for="id_note">Note:</label>
                                {{ form.note }}
            	               <p class="minor">*Email notifications will only be sent if task is assigned to someone besides yourself.</p>
            	           </td>
             	       </tr>
            	    </table>

                    <input type="hidden" name="priority" value="999" id="id_priority">
                    <input type="hidden" name="created_by" value="{{ request.user.id }}" id="id_created_by">
                    <input type="hidden" name="list" value="{{ list.id }}" id="id_list">
                    <input type="hidden" name="created_date" value="{{ created_date }}" id="id_created_date">
            	    <p><input type="submit" name="add_task" value="Add task" class="todo-button"></p>
                </div>
            {% endif %}

            {% if not view_completed %}

            	<h3>Incomplete tasks :: Drag rows to set priorities</h3>

            	<table border="0" id="tasktable">
                    <tr>
                        <th>Done</th>
                        <th>Task</th>
                        <th>Created</th>
                        <th>Due on</th>
                        <th>Owner</th>
                        <th>Assigned</th>
                        <th>Note</th>
                        <th>Comm</th>
                        {% if list_slug == "mine" %}
                            <th>List</th>
                        {% endif %}
                        <th>Del</th>
                    </tr>
            		{% for task in task_list %}
            	        <tr id="{{ task.id }}">
            	            <td><input type="checkbox" name="mark_done" value="{{ task.id }}" id="mark_done_{{ task.id }}">   </td>
            	            <td><a href="{% url 'todo-task_detail' task.id %}">{{ task.title|truncatewords:20 }}</a></td>
            	            <td>{{ task.created_date|date:"m/d/Y" }}</td>
            	            <td>
            	            {% if task.overdue_status %}<span class="overdue">{% endif %}
            	                {{ task.due_date|date:"m/d/Y" }}
            	            {% if task.overdue_status %}</span>{% endif %}
            	            </td>
            	            <td>{{ task.created_by }}</td>
            	            <td>{% if task.assigned_to %}{{ task.assigned_to }}{% else %}Anyone{% endif %}</td>
            	            <td style="text-align:center;">{% if task.note %}&asymp;{% endif %} </td>
            	            <td style="text-align:center;">{% if task.comment_set.all.count != 0 %}{{ task.comment_set.all.count }}{% endif %}</td>
            	            {% if list_slug == "mine" %}
                                <td><a href="{% url 'todo-incomplete_tasks' task.list.id task.list.slug %}">{{ task.list }}</a></td>
                            {% endif %}
            	            <td><input type="checkbox" name="del_tasks" value="{{ task.id }}" id="del_task_{{ task.id }}">   </td>
                        </tr>
            	    {% endfor %}
            	</table>

                <p><input type="submit" name="mark_tasks_done" value="Continue..."  class="todo-button"></p>
                <p><a  class="todo" href="{% url 'todo-completed_tasks' list_id list_slug %}">View completed tasks</a></p>

            {% else %}

            	<h3>Completed tasks</h3>

            	<table border="0"  id="tasktable">
                    <tr>
                        <th>Undo</th>
                        <th>Task</th>
                        <th>Created</th>
                        <th>Completed on</th>
                        <th>Note</th>
                        <th>Comm</th>
                        {% if list_slug == "mine" %}
                            <th>List</th>
                        {% endif %}
                        <th>Del</th>
                    </tr>

            		{% for task in completed_list %}
            	        <tr>
            	            <td><input type="checkbox" name="undo_completed_task" value="{{ task.id }}" id="id_undo_completed_task{{ task.id }}">   </td>
            	            <td><a href="{% url 'todo-task_detail' task.id %}">{{ task.title|truncatewords:20 }}</a></td>
            	            <td>{{ task.created_date|date:"m/d/Y" }}</td>
            	            <td>{{ task.completed_date|date:"m/d/Y" }}</td>
            	            <td style="text-align:center;">{% if task.note %}&asymp;{% endif %} </td>
            	            <td style="text-align:center;">{% if task.comment_set.all.count != 0 %}{{ task.comment_set.all.count }}{% endif %}
            	            <td><input type="checkbox" name="del_tasks" value="{{ task.id }}" id="del_task_{{ task.id }}">   </td>
                        </tr>
            	    {% endfor %}

            	</table>
            	<p><input type="submit" name="deldonetasks" value="Continue..."  class="todo-button"></p>
            	</form>
                <p><a class="todo" href="{% url 'todo-incomplete_tasks' list_id list_slug %}">View incomplete tasks</a></p>
            {% endif %}

    	{% if user.is_staff %}
        	{% if list_slug != "mine" %}
        	   <p><a class="todo" href="{% url 'todo-del_list' list.id list_slug %}">Delete this list</a></p>
        	{% endif %}
    	{% endif %}

    {% endif %}
{% endblock %}

todo/templates/todo/view_task.html
{% extends "todo/base.html" %}

{% block title %}Task: {{ task.title }}{% endblock %}

{% block content %}

    <script type="text/javascript">
        $(document).ready(function() {
            // Initially hide the TaskEdit form
            $('#TaskEdit').hide();

            // toggle slide to show the Add Task form when link clicked
            $('#slideToggle').click(function(){
                $(this).siblings('#TaskEdit').slideToggle();
            });
        });
    </script>

    {% if auth_ok %}

        <h2>{{ task }}</h2>

        <form action="" method="POST">
            {% csrf_token %}

            <p id="slideToggle" ><strong>&rarr; Click to edit details &larr;</strong></p>

            <p>
                <strong>In list:</strong> <a href="{% url 'todo-incomplete_tasks' task.list.id task.list.slug %}" class="showlink">{{ task.list }}</a><br />
                <strong>Assigned to:</strong> {% if task.assigned_to %}{{ task.assigned_to.get_full_name }}{% else %}Anyone{% endif %}<br />
                <strong>Created by:</strong> {{ task.created_by.first_name }} {{ task.created_by.last_name }}<br />
                <strong>Due date:</strong>  {{ task.due_date }}<br />
                <strong>Completed:</strong> {{ form.completed }}<br />
            </p>

            {% if task.note %}
                <div class="task_note"><strong>Note:</strong> {{ task.note|safe|urlize|linebreaks }}</div>
            {% endif %}

            <div id="TaskEdit">
                <h3>Edit Task</h3>

                <table>
                    <tr>
                        <td>Title:</td>
                        <td>{{ form.title }}  </td>
                    </tr>

                    <tr>
                        <td>List:</td>
                        <td>{{ form.list }}  </td>
                    </tr>

                    <tr>
                        <td>Due:</td>
                        <td>{{ form.due_date }}  </td>
                    </tr>

                    <tr>
                        <td>Assigned to:</td>
                        <td>{{ form.assigned_to }}  </td>
                    </tr>

                    <tr>
                        <td valign="top">Note:</td>
                        <td>{{ form.note }}  </td>
                    </tr>

                    <tr>
                        <td>Priority:</td>
                        <td>{{ form.priority }}  </td>
                    </tr>

                </table>
                <p><input type="submit" class="todo-button" name="edit_task" value="Edit task"></p>
            </div>

            <hr />

            <h3>Add comment</h3>
            <textarea name="comment-body"></textarea>
            <p><input class="todo-button"type="submit" value="Submit"></p>

        </form>

        <h3>Comments on this task</h3>

        <div class="task_comments">
            {% for comment in comment_list %}
                <p>
                    <strong>{{ comment.author.first_name }} {{ comment.author.last_name }},
                        {{ comment.date|date:"F d Y P" }}
                    </strong>
                </p>
                {{ comment.body|safe|urlize|linebreaks }}
            {% empty %}
                <p>No Comments</p>
            {% endfor %}
        </div>

    {% endif %}

{% endblock %}